# Machine Leaning
## Python Libraries

### Juana Valentina Mendoza Santamaría 
#### juana.mendoza@usantoto.edu.co
#### 2021 

### Notebook contents:

<ol>
  <li>NumPy Library</li>
  <li>Pandas Library</li>
</ol>

## NumPy

Create an array and matrix.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print('a:', a)
b = np.array([(1, 2, 3), (4, 5, 6)])
print('b:')
print(b)

a: [1 2 3]
b:
[[1 2 3]
 [4 5 6]]


Fill matrix with number 1.

In [2]:
# create matrix 3 rows x 5 columns.

matrix1 = np.ones((3, 5))
print(matrix1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Fill matrix with number 0.

In [3]:
# create matrix 3 rows x 5 columns.

matrix1 = np.zeros((3, 5))
print(matrix1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Fill matrix with a specific number.

In [4]:
# create matrix 3 rows x 5 columns.

matrix1 = np.full((3, 5), 5)
print(matrix1)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Fill matrix with random numbers.

In [5]:
# create matrix 3 rows x 5 columns. 

matrix1 = np.random.random((3, 5))
print(matrix1)

[[0.48951843 0.87013511 0.77164977 0.92036184 0.11737116]
 [0.54577537 0.53266412 0.2342575  0.71680597 0.02414917]
 [0.72415362 0.67970192 0.22618212 0.65891515 0.61671401]]


Create an array that starts at 0 and ends at 40 and separate each value by 10.

In [6]:
matrix1 = np.arange(0, 50, 10)
print(matrix1)

[ 0 10 20 30 40]


Create an array of 10 values that starts at 0 and ends at 50.

In [7]:
matrix1 = np.linspace(0, 50, 10)
print(matrix1)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


Create an identity matrix.

In [8]:
matrix1 = np.eye(4, 4)
print(matrix1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(f'Number of array dimensions: {b.ndim}')
print(f'Type: {b.dtype}')
print(f'Number of elements in the array: {b.size}')
print(f'Shape of an array. (row, col): {b.shape}')

Number of array dimensions: 2
Type: int64
Number of elements in the array: 6
Shape of an array. (row, col): (2, 3)


Reshape the matrix.

In [10]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(f'Matrix: \n {b}')

a = b.reshape(3, 2)
print(f'Matrix: \n {a}')

Matrix: 
 [[1 2 3]
 [4 5 6]]
Matrix: 
 [[1 2]
 [3 4]
 [5 6]]


Given the following array, how to print all the elements of the
first row?

In [11]:
matrix1 = np.array([(1, 2, 3, 4, 5, 6), (7, 8, 9, 10, 11, 12)])
print(f'Matrix: \n {matrix1}')

Matrix: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
print(f'First element in the matrix: \n {matrix1[0]}')
print(f'First element in the matrix: \n {matrix1[0, :]}')

First element in the matrix: 
 [1 2 3 4 5 6]
First element in the matrix: 
 [1 2 3 4 5 6]


In [13]:
matrix1 = np.array([(1, 2, 3, 4, 5, 6), (7, 8, 9, 10, 11, 12)])
print(f'Minimun element: {matrix1.min()}')
print(f'Maximun element: {matrix1.max()}')
print(f'Add all elements: {matrix1.sum()}')
print(f'Add lists by position: {matrix1.sum(0)}')
print(f'Add each list separately: {matrix1.sum(1)}')

Minimun element: 1
Maximun element: 12
Add all elements: 78
Add lists by position: [ 8 10 12 14 16 18]
Add each list separately: [21 57]


In [14]:
matrix1 = np.array([(1, 2, 3, 4, 5, 6), (7, 8, 9, 10, 11, 12)])
print(f'Standard deviation: {np.std(matrix1)}')

Standard deviation: 3.452052529534663


In [15]:
matrix1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(f'Standard deviation: {np.std(matrix1)}')

Standard deviation: 3.452052529534663


In [16]:
a = np.array(((1, 2), (3, 4)))
b = np.array(((5, 6), (7, 8)))

print(f'a: \n {a} \n')
print(f'b: \n {b} \n')
print(f'a + b: \n {a + b} \n')
print(f'a - b: \n {a - b} \n')
print(f'a * b: \n {a * b} \n')

a: 
 [[1 2]
 [3 4]] 

b: 
 [[5 6]
 [7 8]] 

a + b: 
 [[ 6  8]
 [10 12]] 

a - b: 
 [[-4 -4]
 [-4 -4]] 

a * b: 
 [[ 5 12]
 [21 32]] 



In [17]:
print(f'a.dot(b): \n {a.dot(b)} \n')
print(f'b.dot(a): \n {b.dot(a)}')

a.dot(b): 
 [[19 22]
 [43 50]] 

b.dot(a): 
 [[23 34]
 [31 46]]


## Pandas


In [18]:
import pandas as pd

data = np.array([
    ["", "Name", "Age"], 
    ["Student1", "Anna", 12],
    ["Student2", "Marry", 9]
])

df = pd.DataFrame(data)
print(df)

          0      1    2
0             Name  Age
1  Student1   Anna   12
2  Student2  Marry    9


In [25]:
print(pd.DataFrame(
    data = data[1:,1:],
    index = data[1:,0],
    columns = data[0,1:]
))

           Name Age
Student1   Anna  12
Student2  Marry   9


In [26]:
print("Shape", df.shape)
print("Stats: \n", df.describe())

Shape (3, 3)
Stats: 
         0     1    2
count   3     3    3
unique  3     3    3
top        Name  Age
freq    1     1    1


In [27]:
data = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

df = pd.DataFrame(data)

print(df)
print("Stats: \n", df.describe())
print("Mean", df.mean())

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
Stats: 
          0    1    2
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0
Mean 0    4.0
1    5.0
2    6.0
dtype: float64
